# Generated by Django 3.1 on 2021-03-19 14:57

from django.db import migrations, models
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_holder_name',
            field=models.TextField(blank=True, help_text='The name of the person or business that owns the bank account.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_city',
            field=models.TextField(blank=True, help_text='City/District/Suburb/Town/Village.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_country',
            field=models.TextField(blank=True, help_text='Billing address country.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_line1',
            field=models.TextField(blank=True, help_text='Street address/PO Box/Company name.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_line1_check',
            field=djstripe.fields.StripeEnumField(blank=True, enum=djstripe.enums.CardCheckResult, help_text='If `address_line1` was provided, results of the check.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_line2',
            field=models.TextField(blank=True, help_text='Apartment/Suite/Unit/Building.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_state',
            field=models.TextField(blank=True, help_text='State/County/Province/Region.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_zip',
            field=models.TextField(blank=True, help_text='ZIP or postal code.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address_zip_check',
            field=djstripe.fields.StripeEnumField(blank=True, enum=djstripe.enums.CardCheckResult, help_text='If `address_zip` was provided, results of the check.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='country',
            field=models.CharField(blank=True, help_text='Two-letter ISO code representing the country of the card.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvc_check',
            field=djstripe.fields.StripeEnumField(blank=True, enum=djstripe.enums.CardCheckResult, help_text='If a CVC was provided, results of the check.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='dynamic_last4',
            field=models.CharField(blank=True, help_text='(For tokenized numbers only.) The last four digits of the device account number.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='fingerprint',
            field=models.CharField(blank=True, help_text='Uniquely identifies this particular card number.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.TextField(blank=True, help_text='Cardholder name.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tokenization_method',
            field=djstripe.fields.StripeEnumField(blank=True, enum=djstripe.enums.CardTokenizationMethod, help_text='If the card number is tokenized, this is the method that was used.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='failure_code',
            field=djstripe.fields.StripeEnumField(blank=True, enum=djstripe.enums.ApiErrorCode, help_text='Error code explaining reason for charge failure if available.', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='failure_message',
            field=models.TextField(blank=True, help_text='Message to user further explaining reason for charge failure if available.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='receipt_email',
            field=models.TextField(blank=True, help_text='The email address that the receipt for this charge was sent to.', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='receipt_url',
            field=models.TextField(blank=True, help_text='This is the URL to view the receipt for this charge. The receipt is kept up-to-date to the latest state of the charge, including any refunds. If the charge is for an Invoice, the receipt will be stylized as an Invoice receipt.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.TextField(blank=True, help_text='Name of the coupon displayed to customers on for instance invoices or receipts.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(blank=True, help_text="The customer's full name or business name.", max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.TextField(blank=True, help_text="The customer's phone number.", max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='idempotency_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hosted_invoice_url',
            field=models.TextField(blank=True, help_text='The URL for the hosted invoice page, which allows customers to view and pay an invoice. If the invoice has not been frozen yet, this will be null.', max_length=799, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.TextField(blank=True, help_text='The link to download the PDF for the invoice. If the invoice has not been frozen yet, this will be null.', max_length=799, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='description',
            field=models.TextField(blank=True, help_text='An arbitrary string attached to the object. Often useful for displaying to users.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='failure_message',
            field=models.TextField(blank=True, help_text='Message to user further explaining reason for payout failure if available.', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nickname',
            field=models.TextField(blank=True, help_text='A brief description of the plan, hidden from customers.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='caption',
            field=models.TextField(blank=True, help_text='A short one-line description of the product, meant to be displayableto the customer. Only applicable to products of `type=good`.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='currency',
            field=djstripe.fields.StripeCurrencyCodeField(blank=True, help_text='Three-letter ISO currency code', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='statement_descriptor',
            field=models.CharField(blank=True, help_text="Extra information about a source. This will appear on your customer's statement every time you charge the source.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upcominginvoice',
            name='hosted_invoice_url',
            field=models.TextField(blank=True, help_text='The URL for the hosted invoice page, which allows customers to view and pay an invoice. If the invoice has not been frozen yet, this will be null.', max_length=799, null=True),
        ),
        migrations.AlterField(
            model_name='upcominginvoice',
            name='invoice_pdf',
            field=models.TextField(blank=True, help_text='The link to download the PDF for the invoice. If the invoice has not been frozen yet, this will be null.', max_length=799, null=True),
        ),
    ]
